// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGT_LMnWdMQyJAIv9DF7K_0TG-IbIaIOg',
    appId: '1:278286653138:web:abef1d4c5413cf69867f0b',
    messagingSenderId: '278286653138',
    projectId: 'glitched-e4413',
    authDomain: 'glitched-e4413.firebaseapp.com',
    storageBucket: 'glitched-e4413.firebasestorage.app',
    measurementId: 'G-ST2XSMR8F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTlIZsrY_1Ryw8QA-awGg7R0b0S6_psQA',
    appId: '1:278286653138:android:378f0034dcea6ec4867f0b',
    messagingSenderId: '278286653138',
    projectId: 'glitched-e4413',
    storageBucket: 'glitched-e4413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl9rjIsUSARc_orVHeKasJNBMW63VfOjM',
    appId: '1:278286653138:ios:270352903fbc43f6867f0b',
    messagingSenderId: '278286653138',
    projectId: 'glitched-e4413',
    storageBucket: 'glitched-e4413.firebasestorage.app',
    iosBundleId: 'com.example.glitched',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl9rjIsUSARc_orVHeKasJNBMW63VfOjM',
    appId: '1:278286653138:ios:270352903fbc43f6867f0b',
    messagingSenderId: '278286653138',
    projectId: 'glitched-e4413',
    storageBucket: 'glitched-e4413.firebasestorage.app',
    iosBundleId: 'com.example.glitched',
  );
}
